BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS users (
    "id" UUID NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "email" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
