name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

concurrency:
  group: golang-checks-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GOLANG_VERSION: "1.24.1"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.extract.outputs.go-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Install tools
        run: |
          mise install
          eval "$(mise activate bash)"

      - name: Run Linters
        run: |
          eval "$(mise activate bash)"
          make lint
          git diff --exit-code

  gosec:
    name: Security Checks
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Install tools
        run: |
          mise install
          eval "$(mise activate bash)"

      - name: Run GoSec
        run: |
          eval "$(mise activate bash)"
          make gosec

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup and Build
        run: |
          eval "$(mise activate bash)"
          make setup
          make compile

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Install tools
        run: |
          mise install
          eval "$(mise activate bash)"

      - name: Run Tests
        run: |
          eval "$(mise activate bash)"
          make test
  # TODO: review this
  # generated_code:
  #   name: Check generated code
  #   runs-on: ubuntu-latest
  #   needs: [ setup ]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         persist-credentials: false
  #
  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: ${{ env.GOLANG_VERSION }}
  #         cache: true
  #         check-latest: true
  #
  #     - name: Check generated code
  #       run: |
  #         make setup
  #         make generate
  #         git diff --exit-code